layout_spectrum: 0.06587783
typography_spectrum: 0.3646413
color:
  saturation: 0.5690321
  lightness: 0.7763771
  brandStrength: 0.493617
  brandColors:
    - '#F9F9F9'
    - '#DF9A80'
    - '#1F4C87'
    - '#050404'
    - '#C4CFBF'
  rhythmicContrast: 0.5268605
name: Robert Iurato
