name: Robert Iurato
favicon: null
layout_spectrum: 0.06587783
typography_spectrum: 0.3646413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F9F9F9'
    - '#DF9A80'
    - '#1F4C87'
    - '#050404'
    - '#C4CFBF'
  brandStrength: 0.493617
  lightness: 0.7763771
  saturation: 0.5690321
  rhythmicContrast: 0.5268605
purpose: []
